version: '2'
services:
  odoo:
    image: pesol/odoo-run:11
    ports:
      - 8069:8069
      - 8079:8079
    volumes:
      - .:/opt
    depends_on:
      - postgres
      - wdb
  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - ./db:/var/lib/postgresql/data:z
  wdb:
    image: yajo/wdb-server
    ports:
      - "127.0.0.1:1984:1984"
